#ifndef	MISCFIXESSSE_VERSION_INCLUDED
#define MISCFIXESSSE_VERSION_INCLUDED

#define MISCFIXESSSE_MAKE_STR_HELPER(x) #x
#define MISCFIXESSSE_MAKE_STR(x) MISCFIXESSSE_MAKE_STR_HELPER(x)

#define MISCFIXESSSE_VERSION_MAJOR		1
#define MISCFIXESSSE_VERSION_MINOR		1
#define MISCFIXESSSE_VERSION_PATCH		0
#define MISCFIXESSSE_VERSION_BETA		0
#define MISCFIXESSSE_VERSION_VERSTRING	MISCFIXESSSE_MAKE_STR(MISCFIXESSSE_VERSION_MAJOR) "." MISCFIXESSSE_MAKE_STR(MISCFIXESSSE_VERSION_MINOR) "." MISCFIXESSSE_MAKE_STR(MISCFIXESSSE_VERSION_PATCH) "." MISCFIXESSSE_MAKE_STR(MISCFIXESSSE_VERSION_BETA)

#endif
